[package]
name = "zkper-base"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = { workspace = true, features = ["num-traits"] }
rand.workspace = true
rand_chacha.workspace = true
primal.workspace = true
num-traits.workspace = true
anyhow.workspace = true
thiserror.workspace = true
