[package]
name = "zkper-curves"
version = "0.1.0"
edition = "2021"

[dependencies]
zkper-base.workspace = true

lazy_static.workspace = true
rug = { workspace = true, features = ["integer", "num-traits"] }
rand_core.workspace = true
