[package]
name = "zkper-integer"
version = "0.1.0"
edition = "2021"

[dependencies]
zkper-rand.workspace = true

anyhow.workspace = true

rand.workspace = true
rand_core.workspace = true
num-traits.workspace = true
rug = { workspace = true, features = ["num-traits"] }
